spring:
  profiles:
    active:
    - dev

---
server:
  port: 10010

spring:
  application:
    name: file-service
  servlet:    multipart:      max-file-size: 10MB
      max-request-size: 10MB
    
security:
  oauth2:
    client:
      id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key # authorization server와 동일하게 셋팅해야 함

file:
  basepath: /volume1/file    